SF/force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF/force-app/main/default/objects/Project__c/fields/Percentage_Complete__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Complete__c</fullName>
    <label>Percentage Complete</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

SF/force-app/main/default/objects/Project__c/fields/Status_Flag__c.field-meta.xml
<CustomField>
    <fullName>Status_Flag__c</fullName>
    <formula>IF(ISPICKVAL(Status__c, &apos;In Progress&apos;), IMAGE(&quot;/resource/InProgressImage&quot;, &quot;In Progress&quot;,30,30),
    IF(ISPICKVAL(Status__c, &apos;Completed&apos;), IMAGE(&quot;/resource/CompletedImage&quot;, &quot;Completed&quot;,30,30),
        IF(ISPICKVAL(Status__c, &apos;Not Started&apos;), IMAGE(&quot;/resource/PendingImage&quot;, &quot;Not Started&quot;,30,30),
            IMAGE(&quot;/resource/DefaultImage&quot;, &quot;Not Started&quot;,30,30)
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Flag</label>
    <type>Text</type>
</CustomField>

SF/force-app/main/default/objects/To_Do_Items__c/To_Do_Items__c.object-meta.xml
<CustomObject>
    <label>To-Do Items</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To-Do Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SF/force-app/main/default/objects/To_Do_Items__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>To-Do Items</relationshipLabel>
    <relationshipName>To_Do_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

SF/force-app/main/default/classes/ProjectInfoHandler.cls
public with sharing class ProjectInfoHandler {
    
  
    
    @AuraEnabled(cacheable=TRUE)
    public static List<Project__c> retrieveProjectRecords(){
        List<Project__c> prjList = [SELECT Id, Name, Status__c,Status_Flag__c, Percentage_Complete__c, Description__c FROM Project__c WHERE Name != NULL];
        RETURN prjList;
    }
 
 
    @AuraEnabled(cacheable=TRUE)
    public static List<Milestone__c> retrieveMilestoneRecords(string prjId){
      List<Milestone__c> mileObj = new  List<Milestone__c>();
      List<Milestone__c> mileList = [SELECT Id, Name, Status__c, Due_Date__c,Status_Flag__c, Percentage_Complete__c, Project__c,Project__r.Name FROM Milestone__c WHERE Project__c=:prjId];
      FOR(Milestone__c mile:mileList){
        mileObj.add(mile);
      }
      return mileObj;
    }

    @AuraEnabled(cacheable=TRUE)
    public static List<To_Do_Items__c> retrieveTodoRecords(string milstoneId){
      List<To_Do_Items__c> mileObj = new  List<To_Do_Items__c>();
      List<To_Do_Items__c> mileList = [SELECT Id, Name, Status__c, Milestone__c,Milestone__r.Name FROM To_Do_Items__c WHERE Milestone__c=:milstoneId];
      FOR(To_Do_Items__c mile:mileList){
        mileObj.add(mile);
      }
      return mileObj;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<DataSet> getCount(){
      List<Project__c> prjList = [SELECT Id, Name, Status__c,Status_Flag__c, Percentage_Complete__c, Description__c FROM Project__c WHERE Name != NULL];
      List<Milestone__c> mileList = [SELECT Id, Name, Status__c, Due_Date__c,Status_Flag__c, Percentage_Complete__c, Project__c,Project__r.Name FROM Milestone__c WHERE Name != NULL];
      List<To_Do_Items__c> toDoList = [SELECT Id, Name, Status__c, Milestone__c,Milestone__r.Name FROM To_Do_Items__c WHERE Name != NULL];
      List<DataSet> dataSet = new List<DataSet>();
      dataSet.add(new DataSet('Project' ,prjList.size()));
      dataSet.add(new DataSet('Milestone' ,mileList.size()));
      dataSet.add(new DataSet('TodoList' ,toDoList.size()));
     return dataSet;
    }
    
    public class DataSet{
      @AuraEnabled
      public  String label {get;set;}
      
      @AuraEnabled
      public  Integer  count {get;set;}
      
      public DataSet(String label ,Integer count){
                    this.label  = label ;
                    this.count = count ;
          }
    }
    
   
}